<!DOCTYPE html>
<html lang="<?= $this->config('i18n.locale') ?>">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="generator" content="<?= $this->option('service.branding.name') ?>">
    <meta name="publisher" content="<?= $this->option('client.name.full') ?>">
    <meta name="description" content="<?= $this->option('service.meta.description') ?>">
    <link type="image/x-icon" rel="icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
    <link type="image/x-icon" rel="shortcut icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/jquery-ui/jquery-ui.min.css') ?>" media="all">
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/default.min.css') ?>" media="all">
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css-client/default.css') ?>" media="all">
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/tailwind-theme.css') ?>" media="all">
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/tailwind.css') ?>" media="all">
    <?= $this->headLink() ?>
    <?= $this->headTitle($this->option(['client.name.short', 'service.name.full']))->setSeparator(' &middot; ')->setAutoEscape(false) ?>
</head>

<body>
    <div id="header" class="no-wrap no-print" <?= $this->headerAttributes() ?>>

    </div>

    <div id="content">
        <?= $this->messages() ?>

        <?= $this->tabs() ?>

        <div class="content-panel <?= $this->placeholder('panel') ?>">
            <?= $this->content ?>
        </div>

        <?= $this->links() ?>
    </div>

    <div id="footer">

    </div>

    <script type="text/javascript" src="<?= $this->basePath('js/jquery/jquery.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('js/jquery-ui/jquery-ui.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('js/default.min.js') ?>"></script>
    <?= $this->headScript() ?>
</body>

</html>